### ISSUE TITLE
Live plotting is not working. It was working on my Fedora 22 personal computer, but it does not work on Ubuntu LTS 14.04 32 bit. 

### ISSUE THREAD

**Issue by mflor35** [mflor35/Summer2015#13]
@kapilsinha Can you help me run graph_data.py in DataAnalysis and see if you get the same issue?

**Comment by kapilsinha** [comment]
Of course

**Comment by kapilsinha** [comment]
The program worked on my computer (Ubuntu 14.04 LTS 64-bit) and properly created the graph. The problem is probably that the laptop itself cannot process the data. Nonexistent bug fixed!

**Comment by mflor35** [comment]
I wonder if we are using the same version of matplotlib. Maybe this old macbook with ubuntu 14.04 32-bit cannot handle the load.

**Comment by mflor35** [comment]
Bug is only on old macbook running Ubuntu LTS 32bit.

**Comment by kapilsinha** [comment]
Turn it in if you can 


     On Monday, July 27, 2015 9:51 AM, Miguel Flores Silverio <notifications@github.com> wrote:
   

 Closed #13.—

**Comment by mflor35** [comment]
You replied to the wrong email @kapilsinha!
